(herald constants)

(define-constant S1 0)
(define-constant S2 1)
(define-constant S3 2)
(define-constant S4 3)
(define-constant NARGS 3)
(define-constant P 4)
(define-constant A1 5)
(define-constant A2 6)
(define-constant A3 7)
(define-constant A4 8)
(define-constant A5 9)
(define-constant TP -1)
(define-constant nil-reg -2)
(define-constant XP -3)
(define-constant SP -4)

(define-constant tag/pair 3)
(define-constant tag/extend 2)
